language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - git clone https://github.com/cakephp/app.git ../app && cd ../app
  - composer install --no-interaction
  - cp config/app.default.php config/app.php
  - mkdir -p plugins/SyntaxEra
  - mv ../cakephp-sparkpost-plugin plugins/SyntaxEra/SparkPost
  - cp plugins/SyntaxEra/SparkPost/phpunit.xml.dist ./phpunit.xml.dist

script:
  - mkdir -p tmp/build/coverage
  - ./vendor/bin/phpunit

after_success:
  - php ./vendor/bin/coveralls -v
